USE [master]
GO

/****** Object:  Database [УП1221]    Script Date: 14.11.2025 0:33:46 ******/
CREATE DATABASE [УП1221]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'УП1221', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\УП1221.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'УП1221_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\УП1221_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [УП1221].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [УП1221] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [УП1221] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [УП1221] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [УП1221] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [УП1221] SET ARITHABORT OFF 
GO

ALTER DATABASE [УП1221] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [УП1221] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [УП1221] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [УП1221] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [УП1221] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [УП1221] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [УП1221] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [УП1221] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [УП1221] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [УП1221] SET  ENABLE_BROKER 
GO

ALTER DATABASE [УП1221] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [УП1221] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [УП1221] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [УП1221] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [УП1221] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [УП1221] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [УП1221] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [УП1221] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [УП1221] SET  MULTI_USER 
GO

ALTER DATABASE [УП1221] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [УП1221] SET DB_CHAINING OFF 
GO

ALTER DATABASE [УП1221] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [УП1221] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [УП1221] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [УП1221] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [УП1221] SET QUERY_STORE = ON
GO

ALTER DATABASE [УП1221] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [УП1221] SET  READ_WRITE 
GO


USE [УП1221]
GO

/****** Object:  Table [dbo].[MaterialType]    Script Date: 14.11.2025 0:35:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MaterialType](
	[MaterialTypeName] [nvarchar](50) NOT NULL,
	[MaterialDefective] [nvarchar](50) NOT NULL,
	[MaterialTypeId] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_Material_type_import] PRIMARY KEY CLUSTERED 
(
	[MaterialTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [УП1221]
GO

/****** Object:  Table [dbo].[Materials]    Script Date: 14.11.2025 0:35:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Materials](
	[MaterialName] [nvarchar](100) NOT NULL,
	[MaterialUnitPrice] [decimal](18, 2) NOT NULL,
	[WarehouseQuantity] [decimal](18, 2) NOT NULL,
	[MinQuantity] [decimal](18, 2) NOT NULL,
	[PackageQuantity] [int] NOT NULL,
	[MeasurementUnit] [nvarchar](10) NOT NULL,
	[MaterialId] [int] IDENTITY(1,1) NOT NULL,
	[MaterialTypeId] [int] NOT NULL,
 CONSTRAINT [PK_Materials_import] PRIMARY KEY CLUSTERED 
(
	[MaterialId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Materials]  WITH CHECK ADD  CONSTRAINT [FK_Materials_import_Material_type_import] FOREIGN KEY([MaterialTypeId])
REFERENCES [dbo].[MaterialType] ([MaterialTypeId])
GO

ALTER TABLE [dbo].[Materials] CHECK CONSTRAINT [FK_Materials_import_Material_type_import]
GO


USE [УП1221]
GO

/****** Object:  Table [dbo].[ProductType]    Script Date: 14.11.2025 0:37:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ProductType](
	[ProductTypeName] [nvarchar](50) NOT NULL,
	[ProductTypeCoefficient] [float] NOT NULL,
	[ProductTypeId] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_Product_type_import] PRIMARY KEY CLUSTERED 
(
	[ProductTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [УП1221]
GO

/****** Object:  Table [dbo].[Products]    Script Date: 14.11.2025 0:37:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Products](
	[ProductName] [nvarchar](100) NOT NULL,
	[Article] [int] NOT NULL,
	[MinCostPartner] [decimal](18, 2) NOT NULL,
	[RollWidthM] [decimal](18, 2) NOT NULL,
	[ProductId] [int] IDENTITY(1,1) NOT NULL,
	[ProductTypeId] [int] NOT NULL,
 CONSTRAINT [PK_Products_import] PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Products]  WITH CHECK ADD  CONSTRAINT [FK_Products_import_Product_type_import1] FOREIGN KEY([ProductTypeId])
REFERENCES [dbo].[ProductType] ([ProductTypeId])
GO

ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Products_import_Product_type_import1]
GO


USE [УП1221]
GO

/****** Object:  Table [dbo].[ProductMaterials]    Script Date: 14.11.2025 0:35:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ProductMaterials](
	[RequiredQuantity] [decimal](18, 2) NOT NULL,
	[ProductMaterialId] [int] IDENTITY(1,1) NOT NULL,
	[ProductId] [int] NOT NULL,
	[MaterialId] [int] NOT NULL,
 CONSTRAINT [PK_Product_materials_import] PRIMARY KEY CLUSTERED 
(
	[ProductMaterialId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ProductMaterials]  WITH CHECK ADD  CONSTRAINT [FK_Product_materials_import_Materials_import] FOREIGN KEY([MaterialId])
REFERENCES [dbo].[Materials] ([MaterialId])
GO

ALTER TABLE [dbo].[ProductMaterials] CHECK CONSTRAINT [FK_Product_materials_import_Materials_import]
GO

ALTER TABLE [dbo].[ProductMaterials]  WITH CHECK ADD  CONSTRAINT [FK_Product_materials_import_Products_import] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Products] ([ProductId])
GO

ALTER TABLE [dbo].[ProductMaterials] CHECK CONSTRAINT [FK_Product_materials_import_Products_import]
GO


USE [УП1221]
GO

/****** Object:  Table [dbo].[Users]    Script Date: 14.11.2025 0:37:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Users](
	[Role] [nvarchar](50) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Login] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[UserImageBytes] [image] NULL,
 CONSTRAINT [PK_User_import] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


